### ISSUE TITLE
Merge with Celeste?

### ISSUE THREAD

**Issue by yioannides** [pieterdd/RcloneShuttle#12]
Hello! Considering [Celeste](https://github.com/hwittenborn/celeste) and your project are both GTK4 frontends for Rclone written in Rust, it might be beneficial to merge your work with the Celeste repo, in order to have a better change of expanding on this concept together than do the exact same thing separately.

It's just a humble suggestion, of course feel free to close this issue at any point.

**Comment by pieterdd** [comment]
Hi there! While both indeed have overlaps in the technologies they build on, I consider Celeste and Rclone Shuttle to be complementary tools with distinct use cases.

Rclone Shuttle lets you use Rclone remotes in a file explorer context, while avoiding the caveats of actually mounting remotes on your filesystem. Celeste is, as far as I can tell, a Dropbox-style tool that keeps Rclone targets in sync.

One aspect of the Unix philosophy is to make each program do one thing well. According to Zawinski's law, every program attempts to expand until it can read mail. I strive not to do that. So right now, I think the best focus for Rclone Shuttle is to be a file explorer for Rclone remotes.
